"""
ProjectRepository defines the data access interface for projects.

Implementations will use SQLModel for database operations.
"""

from abc import ABC, abstractmethod
from typing import Optional, List


from app.projects.schemas import Project, ProjectCreate, ProjectUpdate
from app.auth.schemas import User


class ProjectRepository(ABC):
    """Abstract interface for project persistence operations.

    This contract defines the storage-facing methods used by the project
    service layer. Implementations are responsible for translating project
    schemas to and from the underlying persistence model while keeping
    business rules outside the repository boundary.
    """
    
    @abstractmethod
    async def create(self, project_data: ProjectCreate) -> Project:
        """Persist a new project record and return the stored project.

        Implementations should insert a new project using the validated
        creation payload and return the resulting project schema, including
        any values generated by the database.

        :param project_data: Project creation payload containing the fields
            required to create a new project record.
        :return: The stored project schema enriched with generated fields such
            as identifiers or timestamps.
        """
        ...
    
    @abstractmethod
    async def get_by_id(self, project_id: int) -> Optional[Project]:
        """Return a project by primary key, or ``None`` when not found.

        :param project_id: Database identifier of the project to retrieve.
        :return: The matching project schema when a record exists, otherwise
            ``None``.
        """
        ...
    
    @abstractmethod
    async def list(self, skip: int = 0, limit: int = 100) -> List[Project]:
        """Return a paginated list of project records.

        :param skip: Number of matching project records to omit before
            collecting results.
        :param limit: Maximum number of project records to return.
        :return: A list of project schemas ordered according to the
            implementation's default listing strategy.
        """
        ...

    @abstractmethod
    async def edit(self, project_id: int, project_data: ProjectUpdate, user: User) -> Optional[Project]:
        """Apply partial updates to a project and return the refreshed project.

        Implementations should mutate only the fields explicitly present in
        ``project_data`` and persist the changes. When no project exists for
        the provided id, ``None`` should be returned.

        :param project_id: Database identifier of the project to update.
        :param project_data: Partial payload containing only fields to update.
        :return: The refreshed project schema, or ``None`` if the target
            project does not exist.
        """
        ...
    
    @abstractmethod
    async def get_by_repository_url(self, url: str) -> Optional[Project]:
        """Return the project associated with a unique repository URL.

        This lookup supports flows that need to prevent duplicate repository
        registrations or resolve a project from its source repository.

        :param url: Unique repository URL used to identify a stored project.
        :return: The matching project schema when a record exists, otherwise
            ``None``.
        """
        ...
    
    @abstractmethod
    async def list_help_wanted(self, skip: int = 0, limit: int = 100) -> List[Project]:
        """Return paginated projects currently marked as accepting help.

        :param skip: Number of matching help-wanted project records to omit
            before collecting results.
        :param limit: Maximum number of help-wanted project records to return.

        :return: A list of project schemas whose ``help_wanted`` flag is set
            to ``True``.
        """
        ...
    
    @abstractmethod
    async def delete_by_id(self, project_id: int, user: User) -> bool:
        """Delete a project by primary key.

        :param project_id: Database identifier of the project to delete.
        :param user: The user attempting to delete the project.
        :return: True if the project was deleted, False if not found.
        """
        ...
