from typing import AsyncGenerator
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlmodel import SQLModel

class DatabaseEngine:
    """
    Manages the database connection and session creation for the application.
    
    This class encapsulates the SQLAlchemy async engine and sessionmaker,
    providing methods for database initialization and session management.
    """
    
    def __init__(self, database_url: str):
        """
        Initialize the database engine and session factory.
        
        The database URL is supplied by the caller, not resolved inside this module.
        This keeps configuration separate from session management and makes the
        class easier to reuse and test.
        
        :param database_url: The SQLAlchemy database URL to use for engine creation.
        :type database_url: str
        """
        self.database_url = database_url

        # Create the asynchronous engine
        # The `echo=True` parameter is useful for debugging as it logs all the SQL statements generated by SQLAlchemy.
        self.engine = create_async_engine(self.database_url, echo=True)
        
        # Create session factory through sessionmaker
        self.async_session = sessionmaker(
            self.engine, class_=AsyncSession, expire_on_commit=False
        )

    async def init_db(self):
        """
        Initialize the database by creating all tables defined in SQLModel metadata.
        
        Note: This method is intended for development/testing purposes.
        In production, use Alembic migrations for proper schema management.
        """
        async with self.engine.begin() as conn:
            # This creates all databases defined by the SQLModel class
            await conn.run_sync(SQLModel.metadata.create_all)

    async def get_session(self) -> AsyncGenerator[AsyncSession, None]:
        """
        Provide a database session as a FastAPI dependency.
        
        This is an async generator that yields a database session for use in FastAPI routes.
        The session is automatically closed when the request completes.
        
        Yields:
            AsyncSession: An active database session
        """
        async with self.async_session() as session:
            yield session
